language: python
python:
  - 2.7
  - 3.6

# Setup anaconda
install:
  - pip install -r .travis.requirements.txt
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install gfortran
  - sudo apt-get install gcc
  - sudo apt-get install build-essential
  - sudo apt-get install cmake
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install git
  - git clone https://github.com/pyne/pyne
  - cd pyne
  - sudo python setup.py install --user
# command to run tests
script:
  - python ./scripts/test_write_input.py
  - python ./scripts/test_analysis.py