language: python
python:
  - 2.7
  - 3.3
  - 3.6

# Setup anaconda
install:
  - pip install -r .travis.requirements.txt
# command to run tests
script:
  - python ./scripts/test_write_input.py
  - python ./scripts/test_analysis.py