language: python
python:
  - 2.7
  - 3.3
  - 3.6

# Setup anaconda
install:
  - sudo apt-get install -y python-matplotlib
  - sudo apt-get install -y python-jinja2
  - sudo apt-get install -y python-numpy

# command to run tests
script:
  - python ./scripts/test_write_input.py
  - python ./scripts/test_analysis.py